config/routes.rb
Rails.application.routes.draw do

  root "sessions#homepage"

  get '/auth/:google_oauth2/callback', to: "sessions#omniauth"
  # get 'auth/failure', to: redirect('/')
  get '/product_category', to: "products#product_category"

  resources :products, only: [:index, :show, :new, :create, :edit, :update]
  resources :reviews
  resources :users

  resources :products, only: [:show] do
    resources :reviews, only: [:index, :show, :new]
  end
  
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/*path', to: "sessions#homepage"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :reviews
    has_many :users, through: :reviews
    validates_presence_of :name, :brand, :price, :category
    validates_uniqueness_of :name

    # scope: products_of_one_brand ->(skincare_brand) { where(brand: skincare_brand) }
    # scope: most_reviewed_product ->()
    # scope :highest_rated, ->(rate) {where("reviews.rating = ?", rate)}

    scope :product_category, ->(product_type) {where("category = ?", product_type)}

    PRICE = ["$", "$$", "$$$"]

    CATEGORY = ["Cleanser", "Moisturizer", "Serum", "Spray", "Sunscreen", "Toner", "Exfoliant", "Other"]

end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :product
    belongs_to :user
    validates_presence_of :review_body, :rating

    RATING = [
        "1", "2", "3", "4", "5"
    ]


end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :products, through: :reviews

    has_secure_password

    validates_uniqueness_of :email
    validates_presence_of :email, :password, :first_name, :last_name
    validates_length_of :password, in: 6..40

    def self.from_omniauth(response)
        User.find_or_create_by(uid: response[:uid]) do |u|
            u.email = response[:info][:email]
            u.password = SecureRandom.hex(15)
            u.first_name = response[:info][:first_name]
            u.last_name = response[:info][:last_name]
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include ApplicationHelper
    helper_method :current_user, :set_current_user, :logged_in, :set_product, :require_login, :set_review, :flash_alert?

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :set_product, only: [:show, :edit, :update]
    before_action :require_login, only: [:new, :edit]

    def index
        @products = Product.all
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.create(product_params)
        if @product.save
            redirect_to product_path(@product), alert: "Product successfully created!"
        else
            render :new
        end
    end

    def show
        if @product.nil?
            redirect_to products_path
        else
            render :show
        end
    end

    def edit
    end

    def update
        if @product.update(product_params)
            redirect_to product_path(@product)
        else
            render :edit
        end
    end

    def product_category
        @cleansers = Product.product_category("Cleanser")
        @moisturizers = Product.product_category("Moisturizer")
    end

    private

    def product_params
        params.require(:product).permit(:name, :category, :brand, :price)
    end    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_current_user, only: [:new, :create, :edit, :update]
    before_action :set_review, only: [:show, :edit, :update, :destroy]
    before_action :require_login, only: [:new, :edit, :destroy]

    def index
        if params[:product_id] && @product = Product.find(params[:product_id])
            @reviews = @product.reviews
        else
            @reviews = Review.all
        end
    end

    def new
        if params[:product_id] && @product = Product.find(params[:product_id])
            @review = Review.new(product_id: params[:product_id])
        else
            @review = Review.new
        end
    end

    def create
        @review = Review.new(review_params)
        if @review.save
            redirect_to review_path(@review)
        else
            render :new
        end
    end

    def show
        if @review.nil?
            redirect_to reviews_path
        else
            render :show
        end
    end

    def edit
    end

    def update
        @review.update(review_params)
        if @review.save
            redirect_to review_path(@review)
        else
            render :edit
        end
    end

    

    def destroy
        @review.delete
        redirect_to reviews_path
    end

    private

    def review_params
        params.require(:review).permit(:rating, :review_body, :image, :user_id, :product_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def homepage
    end

    def new
    end

    def create
        user = User.find_by(email: params[:user][:email])
        @user = user.try(:authenticate, params[:user][:password])
        if @user
            session[:user_id] = @user.id
            redirect_to user_path(@user), alert: "Login Successful!"
        else
            redirect_to login_path, alert: "Login Unsuccessful, Try Again"
        end
    end

    def omniauth
        @user = User.from_omniauth(request.env['omniauth.auth'])
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to login_path
        end
    end

    def destroy
        session.clear
        redirect_to root_path, alert: "You have logged out!"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    helper_method :set_current_user
    before_action :set_current_user, only: [:edit, :update, :show, :destroy]


    def new #signup
        @user = User.new
    end
    
    def create
        @user = User.create(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(current_user)
        else
            render :new
        end
    end

    def show #profile page
        if @user != nil
            render :show
        else
            redirect_to root_path
        end
    end

    def edit
    end

    def update
        @user.update(user_params)
        if @user.valid?
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        @user.delete
        redirect_to root_path
    end
    
    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :age, :skin_type)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    
    def current_user
        User.find_by(id: session[:user_id])
    end

    def set_current_user
        @user = current_user
    end

    def logged_in
        !!session[:user_id]
    end

    def require_login
        redirect_to login_path unless session.include?(:user_id)
    end

    def skin_types
        ["Normal", "Dry", "Oily", "Combination"]
    end

    def set_product
        @product = Product.find_by(id: params[:id])
    end

    def set_review
        @review = Review.find_by(id: params[:id])
    end

    def flash_alert?
        if flash[:alert]
            flash[:alert]
        end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper

    def full_name
        [first_name, last_name].join(" ").titleize
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkincareCentral</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
    <div class="navbar-left">
      <%= link_to "See all Reviews", reviews_path %> | 
      <%= link_to "See all Products", products_path %> | 
      <%= link_to "See Products by Category", product_category_path %> |
      <% if logged_in %>
        <%= link_to "Create New Product", new_product_path %> | 
        <%= link_to "Create New Review", new_review_path %> |
        <%= link_to "My Profile", user_path(current_user) %> |
        <%= link_to "Log Out", logout_path, method: :post %>
      <% else %>
        <%= link_to "Sign Up", new_user_path %> | 
        <%= link_to "Log In", login_path %> 
      <% end %>
    </div>
    <br>
    <%= flash_alert? %>
    <br>
    <h1>Skincare Central</h1>
  
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :category %>
    <%= f.select :category, options_for_select(Product::CATEGORY), {inlcude_blank: true} %><br><br>
    <%= f.label :brand %>
    <%= f.text_field :brand %><br><br>
    <%= f.label :price %>
    <%= f.select :price, options_for_select(Product::PRICE), {include_blank: true} %><br><br>
    <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h2>Edit <%= @product.name %>:<h2>
<%= render partial: "users/errors", locals: {object: @product} %>
<%= render "form" %>

app/views/products/index.html.erb
<h2>All Products:</h2>

<ul>
<% @products.each do |product| %>
    <li><%= link_to product.name, product_reviews_path(product) %><li>
<% end %>
</ul>

app/views/products/new.html.erb
<h3>Create New Product:</h3>
<%= render partial: "users/errors", locals: {object: @product} %>
<br><br>
<%= render 'form' %>

app/views/products/product_category.html.erb
<h3>All Reviewed Cleansers</h3>
<% @cleansers.each do |p| %>
    <ul>
    <li><%= link_to p.name, product_path(p) %>
    </ul>
<% end %>

<h3>All Reviewed Moisturizers</h3>
<% @moisturizers.each do |p| %>
    <ul>
    <li><%= link_to p.name, product_path(p) %>
    </ul>
<% end %>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<h4>Brand: <%= @product.brand %></h4>
<h4>Category: <%= @product.category %></h4>
<h4>Price Range: <%= @product.price %></h4>

<br>
<h4>Reviews:</h4>
<% @product.reviews.each do |r| %>
    <ul>
    <li><%= link_to r.rating, product_review_path(@product, r) %> - <%= r.review_body %></li>
    </ul>
<% end %>
<br><br>
<%= link_to "Click Here to Create a Review for This Product", new_product_review_path(@product) %><br><br>
<% if logged_in && current_user %>
    <%= link_to "Edit Product", edit_product_path(@product) %>
    <br><br>
<% end %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <% if params[:product_id] %>
        <%= f.hidden_field :product_id, value: @product.id %>
        <h3>Product: <%= @product.name %></h3>
    <% else %>
        <h4>Select a Product:</h4>
        <%= f.collection_select :product_id, Product.all, :id, :name, {include_blank: true} %>
    <% end %>

    <h4>Create a Review:</h4>
    <%= f.label :rating %>
    <%= f.select :rating, options_for_select(Review::RATING), {include_blank: true} %><br><br>
    <%= f.label :review_body, "Review:" %>
    <%= f.text_area :review_body %><br><br>
    <%= f.submit "Submit" %>

<% end %>

app/views/reviews/edit.html.erb
<h2>Edit the Review</h2>
<%= render partial: "users/errors", locals: {object: @review} %>
<%= render 'form' %>

app/views/reviews/index.html.erb
<h2>All Reviews:</h2>

<% @reviews.each do |r| %>
    <ul>
        <li><%= link_to r.product.name, product_path(r.product) %> - <%= r.rating %></li>
    </ul>
<% end %>

app/views/reviews/new.html.erb
<h2>Create a New Review Here:</h2>

<%= render partial: "users/errors", locals: {object: @review} %>
<br><br>
<%= render 'form' %>

app/views/reviews/show.html.erb
<h2><%= @review.product.name %></h2>
<%= @review.rating %> - <%= @review.review_body %>
<br><br>
<% if current_user.id == @review.user_id %>
    <%= link_to "Edit Review", edit_review_path(@review) %>
    <br><br>
    <%= link_to "Delete Review", review_path(@review), method: :delete %>
<% end %>

app/views/users/_errors.html.erb
<% if object.errors.any? %>
    <div class= "field_with_errors" >
    <h3><%= pluralize(object.errors.count, "error") %> prevented this from saving:
    <ul>
    <% object.errors.full_messages.each do |error| %>
        <li><%= error %></li>
    <% end %>
    </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %><br><br>

    <%= f.label :first_name, "First Name" %>
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name, "Last Name" %>
    <%= f.text_field :last_name %><br>

    <%= f.label :age %>
    <%= f.text_field :age %><br>

    <%= f.label :skin_type, "Skin Type" %>
    <%= f.select :skin_type, options_for_select(skin_types), {include_blank: true} %><br>

    <%= f.submit "Submit" %>

<% end %>

app/views/users/edit.html.erb
<h2>Edit Your Profile:<h2>

<%= render partial: "errors", locals: {object: @user} %>

<%= render "form" %>

app/views/users/new.html.erb
<h2>Add Your User Information:<h2>

<%= render partial: "errors", locals: {object: @user} %>


<%= render 'form' %>

app/views/users/show.html.erb
<h2><%= @user.first_name %>'s Profile</h2>

<h3>Skin Type: <%= @user.skin_type %></h3>
<h3>Age: <%= @user.age %></h3>


<h3>Here are your reviews:</h3>
 <% @user.reviews.each do |r| %>
    <ul>
    <li><%= link_to r.product.name, product_path(r.product) %> - <%= r.review_body %></li>
    </ul>
<% end %>

<% if @user.id == current_user %>
    <%= link_to "Edit Profile", edit_user_path(@user) %>
<% end %>